version: '3.7'
services:
  backend:
    container_name: admin_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
       DATABASE_URL: postgresql://postgres:secret@db:5432/postgres?schema=public
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:12
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
    - 5442:5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data